### ISSUE TITLE
[FEAT] Uniform styling across tabs

### ISSUE THREAD

**Issue by F1r3w477** [Idleon-Companion/IdleonCompanion#108]
**Which categories does your suggestion apply to?**
- [x] UI changes
- [ ] Tracking
- [ ] Calculators
- [ ] Other tools/misc

**Is your feature request related to a problem? Please describe.**
Some tabs have weird color formatting that doesn't really match the rest of the site.

**Describe the solution you'd like**
Create a standard styling layout across the site.
![image](https://user-images.githubusercontent.com/9701525/119250020-c3bc0380-bb62-11eb-8ad6-7b2af1390df2.png)
In the above image, there are 3 circles, those colors are used site-wide, however, they don't seem to reflect the usage across the rest of the site. (As shown below)
![image](https://user-images.githubusercontent.com/9701525/119250040-f1a14800-bb62-11eb-85ce-ff96065306a6.png)
![image](https://user-images.githubusercontent.com/9701525/119250050-fd8d0a00-bb62-11eb-9b52-7d6600b9e164.png)
Additionally, on the builds tab, everything is fairly greyscaled, and some extra color might be interesting on it.
![image](https://user-images.githubusercontent.com/9701525/119250066-1f868c80-bb63-11eb-85ef-9103baaa2b57.png)
Also, highlighting the selected calculator something other than grey might be easier for some people to see right away.
![image](https://user-images.githubusercontent.com/9701525/119250173-d71b9e80-bb63-11eb-8898-943c3edc940d.png)
Personally, I think green buttons for adding stuff to a list would match the site theme. Blue headings like "Inventory" might look nice on the "Builds" tab. I could make a very long list, but I think you get the point.

**What data is needed for the suggestion?**
All data should be present in the current build.

**Additional context**
This is probably an ongoing process, and as stuff is added, I'm sure this will be tweaked continually. I just thought it would be nice to set a standard to follow so changes don't need to be made all the time. 

Hit me up on discord if my late night text wall doesn't make sense ItsDan#6969

**Comment by adapap** [comment]
This is a great idea. I think the best approach is to make a rudimentary style guide that we can keep updated on this repo (in Discussions, for example).
