### ISSUE TITLE
[Bug?] Tasks are set to "default" on close/open browser

### ISSUE THREAD

**Issue by Teglhus** [Idleon-Companion/IdleonCompanion#128]
Tasks are set to default, when closing browser, and opening again (using Chrome, with more or less default settings).

When you login - and load your profile, the tasks you had when saved last time, are loaded, and defaults are gone (if you deleted them). But if you come to the site, and didnt notice the default tasks were back, and you can accidently save your profile on another tab, and get all the default tasks back in your list. I think the cookie dont save your default state on the tasks?

**Comment by adapap** [comment]
Closing, since this might be fixed with the redesign? Please re-open if not resolved in next update.
