### ISSUE TITLE
[Suggestion] - remove the "bar" on the tasks page

### ISSUE THREAD

**Issue by Teglhus** [Idleon-Companion/IdleonCompanion#130]
![image](https://user-images.githubusercontent.com/86340128/123042483-3258df00-d3f7-11eb-87fa-c73adafcdaca.png)

As it looks like a scroller, like on the Calculators page. And there is really no need for it, as its not used on any other page.

**Comment by JillMe** [comment]
![image](https://user-images.githubusercontent.com/42550923/124520258-28b67a80-ddec-11eb-91a0-4268876181fa.png)

It's a progress bar, maybe we can communicate it better by adding diagonal stripes to indicate this or adding a text in the middle that tells you the number of resolved tasks and the number of tasks total?

**Comment by Teglhus** [comment]
Yeah okay. I woule make it just say "0%" when nothing is running, and then add in the percentage of the task running. Should be left aligned :)
