### ISSUE TITLE
[BUG] Add New Task - typing in the textbox hardlocks my entire browser for half a minute per character

### ISSUE THREAD

**Issue by 3ICE** [Idleon-Companion/IdleonCompanion#139]
**What version of the website are you using?**
live

**Describe the bug**
My profiler crashed almost immediately so I can't drill down into what is causing this.

I only saw 41932.0 ms 99.9% total time Event: keyup and beforeinput and Function Call and "s" and Recalculate Style.

**Desktop:**
 - OS: Win10
 - Browser chrome
 - Version latest

**Comment by 3ICE** [comment]
I was able to profile during the lag spike for roughly 3000 ms, here are the potential culprits:

Total Blocking Time: 3458 ms (That's like 100%!) _the main thread was blocked for long enough to prevent input responsiveness._

vendor.276ded7b.js:1

2318.6 ms63.3 % | 2320.3 ms63.3 % | Recalculate Style
-- | -- | -- 
2298.5 ms62.8 % | 2300.2 ms62.8 % | Function Call
2298.5 ms62.8 % | 2300.2 ms62.8 % | Event: input
2298.5 ms62.8 % | 2300.2 ms62.8 % | Event: textInput
2298.5 ms62.8 % | 2300.2 ms62.8 % | Event: keypress
178.5 ms4.9 % | 3386.9 ms92.5 % | Event: visibilitychange


index.1a4f9c2f.js:1

? | 3386.9 ms92.5 % | Event: visibilitychange
-- | -- | --
6.1 ms0.2 % | 3367.3 ms91.9 % | Event: DOMActivate
166.8 ms4.6 % | 3350.6 ms91.5 % | Event: input 
853.2 ms23.3 % | 3160.5 ms86.3 % | Function Call
2298.5 ms62.8 % | 2300.2 ms62.8 % | Recalculate Style

Endless function calls (all anonymous):

1972.1 ms | 0.0 ms | 0.0 ms | Request Idle Callback 
-- | -- | -- | --
1972.1 ms | 0.4 ms | 0.4 ms | Recalculate Style
1972.9 ms | 40.8 ms | 826.9 ms | Event: input 
1972.9 ms | 0.6 ms | 0.6 ms | Function Call
1973.7 ms | 5.3 ms | 5.3 ms | Run Microtasks 
1979.0 ms | 0.3 ms | 1.8 ms | Function Call
1980.9 ms | 0.1 ms | 0.6 ms | Function Call 
1981.5 ms | 0.1 ms | 0.5 ms | Function Call 
... | ... | ... | 1000 more Function Calls

Log:

Event: keypress Warning: Handler took 1158.81 ms
Event: textInput Warning: Handler took 1158.68 ms
Event: input Warning: Handler took 1152.85 ms
Function(anonymous) @ index.1a4f9c2f.js:1
Function Call(anonymous) @ index.1a4f9c2f.js:1
Recalculate Style Warning: Forced reflow is a likely performance bottleneck. Elements Affected: 1
Call Stacks: Recalculation Forced (anonymous)	@	index.1a4f9c2f.js:1 Initiator Reveal First Invalidated

**Comment by adapap** [comment]
New redesign changes our task input textbox. If you still experience issues after the next version launches (probably within a few days from now), feel free to open another issue. Thanks for submitting this bug report!

**Comment by 3ICE** [comment]
New redesign looks awesome, no problem with typing there.

**Comment by 3ICE** [comment]
Unfortunately I encountered this issue just now, on the new live version.

Not going to reopen as I seem to be the only one affected. My computer is not fast enough to play and browse at the same time it seems. (Strangely, typing on other websites seems to work okay. Except youtube comments, those lag too.)

**Comment by 3ICE** [comment]
Followup: Far too many event handlers subscribe to onkeyup/onchange events. I wouldn't mind if statue/stamp costs only recalculated once a second. Try spam-clicking up arrow on a Spinner input element and see what the profiler says. I bet you can make it lag if you click fast enough.
