### ISSUE TITLE
[BUG] BobJoePickle (Pickle Jar) Alchemy Vial is not in game.

### ISSUE THREAD

**Issue by 3ICE** [Idleon-Companion/IdleonCompanion#149]
**What version of the website are you using?**
0.2.3

**Describe the bug**
I fear I wasted over 14000 coins buying useless pickles. After I unlocked every other vial available to me there was nothing else to do but try using my daily rolls on the rare "nothing" pickle. But alas, it's not even implemented. Repro steps:
* Buy a BobJoePickle
* Drop it at the cauldron
* Nothing happens. No floating text, nothing.

* A text popup with roll information should happen. If it lands on 90+ I should get the vial.
* My daily vial chances should also decrease by one, no matter what. But it doesn't...
* According to Idleon Companion Alchemy Vials page, it does "50% Nothing, absolutely nothing"
* * and costs 100 BobJoePickle + 3 water to upgrade.
* This outdated information should be hidden or removed.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

EDIT: Curious, other items say "Item has no vial" in red. But the pickle doesn't do that either... I'm missing a secret, probably. ..

**Comment by adapap** [comment]
Closing because I don't think this is related to the website. If you have a bug about the game, consider posting in the official Legends of Idleon discord.
