### ISSUE TITLE
Some recommended Builds are STILL outdated!

### ISSUE THREAD

**Issue by 3ICE** [Idleon-Companion/IdleonCompanion#176]
# Bug Report: Recommended Build outdated (round 2)

Specifically:
Bowman / Active (~70)
It even claims to be for "Game Version: 1.23" but clearly was made way back in 1.10

It is no longer meta to put only 1 point into active skills. You need to level them much higher, preferably equally.

A low level attack only hits 1-2 monsters. A max level one hits 5-8! Active/AFK play are equally affected by this.

I respec'd into the suggested build and only got like 70k xp/hour.
Previously I was raking in 240k xp/hour using my own "build". (Basically I just level up all active skills to 100.)
Same zone, same gear, same amount of gold food and triple xp potions equipped.
Capped 100% hit chance and 100% survivability with both, obviously.
Yes, I also did make sure all the level 1 skills were equipped on my attacks bar and auto combat can use skills is enabled in options though that last one shouldn't matter for AFK gains.

CTRL+F old:"Put 1 point into the active skills" and replace all occurrences with new:"Level your active damage skills to max"

Idleon Companion Version (see changelog): 0.3.0 (Site Redesign) | August 2021

p.s.: This is a brilliant utility. I recommend it to all my friends:
![image](https://user-images.githubusercontent.com/5385790/132152779-0405d82d-c71d-4e0e-b832-885983ae4f7a.png)

**Comment by 100mars** [comment]
For the EXP numbers, how did you obtain the 70k xp/hour, and 240k xp/hour?
For active builds, your AFK numbers will not be representative of your active EXP/hr. (For example, AFK screen does not take into account mana usage, and so active skills are over-prioritized.)

You would need to time your EXP gain manually over a period of time.

**Comment by 3ICE** [comment]
Valid criticism, this is an active build so I have no business testing its merits by going AFK. I merely looked at the AFK info screen and may have even over dramatized things a little. Active play was not thoroughly tested. Though I'm sure it gives over a million XP based solely on my afk gain rate when multiplied by 5.
Level 75 bowman in fully upgraded and reforged gold/boss gear and +20 all useful stats gold tools. (Yes, rerolled with the ±5 random upgrade stones until I got all +5s in a row, well, mostly.)
Zone: Sandcastles (307+ accuracy needed)
I had no mana issues and even used extra talent points on cooldown reduction.

**Comment by 3ICE** [comment]
Also I'm not sure but I think max level skills use less mana? Feels like it. The level 1 skills do not one-shot half the screen at once, that's for sure.

Also for long periods of time every single mob on screen was dead. Downtime like that worsens active XP gain. (I DO have speedy respawns max-unlocked in merit shop.)

Plus it makes a huge difference whether you auto fight or manually aim skillshots. Auto fight frequently misses directional abilities (fires and wastes them at the wrong time, towards a single enemy, or into the air while you are climbing a rope.)
