### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by Matabeytk** [Idleon-Companion/IdleonCompanion#227]
# Bug Report

**Description**

- Describe the bug that you encountered and steps to reproduce it

- Add screenshots if it is a visual bug

---

**Details**

OS (e.g. Windows, iOS):
Browser (e.g. Chrome, Safari):
Idleon Companion Version (see changelog):

**Comment by Liulangzhe98** [comment]
@Matabeytk If you could give more details about the bug I might be able to help
