### ISSUE TITLE
Error message when trying to make a file for companion.

### ISSUE THREAD

**Issue by N3ss3** [Idleon-Companion/IdleonCompanion#235]
# Bug Report

**Description**

- Describe the bug that you encountered and steps to reproduce it

Hey

I've used the program to make logs for the site. The file for companion gives an error code and the other works just fine. So don't know what the error is sadly.
Used it on both the C drive and the drive where the game is located, no difference.

Attaching the automated logs for you.

Thank you for your work.

- Add screenshots if it is a visual bug

---

**Details**

OS (e.g. Windows, iOS):
Browser (e.g. Chrome, Safari):
Idleon Companion Version (see changelog):
[log_22-08-01_0.txt](https://github.com/Idleon-Companion/IdleonCompanion/files/9236260/log_22-08-01_0.txt)
[log_22-08-01_1.txt](https://github.com/Idleon-Companion/IdleonCompanion/files/9236261/log_22-08-01_1.txt)
[log_22-08-01_2.txt](https://github.com/Idleon-Companion/IdleonCompanion/files/9236262/log_22-08-01_2.txt)
[log_22-08-01_3.txt](https://github.com/Idleon-Companion/IdleonCompanion/files/9236263/log_22-08-01_3.txt)
[log_22-08-01_4.txt](https://github.com/Idleon-Companion/IdleonCompanion/files/9236264/log_22-08-01_4.txt)
[log_22-08-01_5.txt](https://github.com/Idleon-Companion/IdleonCompanion/files/9236265/log_22-08-01_5.txt)

**Comment by Liulangzhe98** [comment]
@N3ss3 This is a problem with Idleon Saver (https://github.com/desophos/idleon-saver), however, companion has not been updated to accept the W4 data format.

**Comment by N3ss3** [comment]
Thank you so much for the answer, I did realise this after reading reddit a
few days ago.

Sorry for taking up your time

/E

Den mån 8 aug. 2022 19:26Thijs ***@***.***> skrev:
